name: aur-publish

on:
  push:
  schedule:
    - cron: "0 2 * * *" # Every day @ 02:00

jobs:
  check-release:
    runs-on: ubuntu-latest
    if: ${{ false }} # Disable for now
    outputs:
      modified: ${{ steps.git-check.outputs.modified }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/drata/agent-releases/releases/latest | jq -r ".tag_name" > current-version.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::"$([ -z "$(git status --porcelain)" ] && echo "false" || echo "true")"
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'ndom91'
          git config --global user.email '7415984+ndom91@users.noreply.github.com'
          git commit -am "New drata-agent $(cat current-version.txt)"
          git push
  aur-publish:
    runs-on: ubuntu-latest
    if: ${{ false }} # ${{ needs.check-release.outputs.modified }} - Disable for now
    needs: check-release
    steps:
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          host='aur.archlinux.org'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
      - name: Update PKGBUILD
        run: |
          ver=$(cat current-version.txt)
          sed "s/pkgver=.*/pkgver=${ver:1}/g" ./pkg/PKGBUILD
          wget https://cdn.drata.com/agent/dist/linux/drata-agent-"${ver:1}".deb
          sha512=$(sha512sum drata-agent-"${ver:1}".deb | cut -d' ' -f1)
          sed "s/sha512sums_x86_64=.*/sha512sums_x86_64=(\"$sha512\")/g" ./pkg/PKGBUILD
          cd pkg
          # TODO: makepkg on Ubuntu :thinking:
          makepkg --printsrcinfo > .SRCINFO
          cd ../
          git subtree push -P pkg aur@aur.archlinux.org:drata-agent.git master
