name: aur-publish

on:
  push:
  schedule:
    - cron: "0 2 * * *" # Every day @ 02:00

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/drata/agent-releases/releases/latest | jq -r ".tag_name" >| current-version.txt
      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "$(git status --porcelain)" ] && echo "false" || echo "true")" >> $GITHUB_ENV
      - name: Echo modified
        run: |
          echo ${{ env.modified }}
          cat current-version.txt
  aur-publish:
    runs-on: ubuntu-latest
    if: ${{ env.modified == 'true' }}
    needs: check-release
    steps:
      - uses: actions/checkout@v4
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          host='aur.archlinux.org'
          ssh-keyscan -H "$host" > ~/.ssh/known_hosts
      - name: Update PKGBUILD
        run: |
          ver=$(cat current-version.txt)
          sed -i "s/pkgver=.*/pkgver=${ver:1}/g" ./pkg/PKGBUILD
          wget https://github.com/drata/agent-releases/releases/download/"${ver:1}"/Drata-Agent-linux.deb
          sha512=$(sha512sum drata-agent-"${ver:1}".deb | cut -d' ' -f1)
          sed -i "s/sha512sums_x86_64=.*/sha512sums_x86_64=(\"$sha512\")/g" ./pkg/PKGBUILD
      - name: Update .SRCINFO
        uses: hapakaien/archlinux-package-action@v2
        with:
          flags: ''
          path: pkg
          namcap: false
          srcinfo: true
      - name: Publish AUR package
        uses: ulises-jeremias/github-actions-aur-publish@v1
        with:
          pkgname: drata-agent
          pkgbuild: ./pkg/PKGBUILD
          assets: ./pkg/*
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
          update_pkgver: false
          # force_push: true
      - name: Update Github Repo
        if: ${{ success() }}
        run: |
          git config --global user.name 'ndom91'
          git config --global user.email '7415984+ndom91@users.noreply.github.com'
          git commit -am "feat: new drata-agent published - $(cat current-version.txt)"
          git push
